version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: salary_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-payroll}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - salary_network

  redis:
    image: redis:7-alpine
    container_name: salary_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - salary_network

volumes:
  postgres_data:
  redis_data:

networks:
  salary_network:
    driver: bridge
