name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies - Backend
        working-directory: ./payroll-backend
        run: npm ci

      - name: Build Backend
        working-directory: ./payroll-backend
        run: npm run build

      - name: Install Dependencies - Frontend
        working-directory: ./payroll-frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./payroll-frontend
        run: npm run build

      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/salaryApp
            git pull origin main
            cd payroll-backend
            npm ci
            npm run build
            pm2 restart payroll-backend || pm2 start npm --name "payroll-backend" -- start
            cd ../payroll-frontend
            npm ci
            npm run build
            pm2 restart payroll-frontend || pm2 start npm --name "payroll-frontend" -- start
